apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-cluster-gitlab-redis-volume
  namespace: gitlab
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gitlab-redis
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
