apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: gitlab
  name: glusterfs-cluster-gitlab-redis-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: /gitlab-redis
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
