apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-cluster-gitlab-git-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gitlab-git
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
