apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-cluster-gitlab-postgresql-volume
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gitlab-postgresql
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
