apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-cluster-gitlab-postgresql-claim
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
