apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: glusterfs-cluster-gitlab-postgresql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
